### ISSUE TITLE
无法上传接口文档

### ISSUE THREAD

**Issue by NoUltimate** [jetplugins/yapix#1]
配置文件只配置了rap2的项目id
![image](https://user-images.githubusercontent.com/32738861/131304189-1b0bfbc7-b46a-498f-bcd0-2b34a2631975.png)
![image](https://user-images.githubusercontent.com/32738861/131303682-f652bd57-479a-439f-a614-70bc5f02ba3b.png)
![image](https://user-images.githubusercontent.com/32738861/131303836-a93ea2eb-a416-4f79-8fd3-30c7e853ea91.png)

**Comment by lkqm** [comment]
这个问题应该是修复了，需要手动安装, 请下载: https://raw.githubusercontent.com/jetplugins/yapix/main/yapix.jar

**Comment by NoUltimate** [comment]
我试了下上传成功了，不过简介的开头和结尾好像多了点东西
![image](https://user-images.githubusercontent.com/32738861/131310641-88a1d7a4-4c09-4741-ad60-1acfb6fa1783.png)

**Comment by lkqm** [comment]
这里是markdown展示代码需要，看看预览里面，目前是这么设计的，下一版本可能会有变动

**Comment by lkqm** [comment]
这里是markdown展示代码需要，看看预览里面，目前是这么设计的，下一版本可能会有变动

**Comment by NoUltimate** [comment]
可能我的rap2比较老不支持markdown，所以预览编辑都把这个显示出来了

**Comment by lkqm** [comment]
那下个版本会取消，感觉这个代码必要不大，对前端来说，目前在细节处理上还是不够，下一个版本会打磨细节和mock, 以及date类型这些，欢迎提出建议

**Comment by NoUltimate** [comment]
嗯，期待改进
