### ISSUE TITLE
没有变更也会提交，yapi会生成一条空白的变更记录

### ISSUE THREAD

**Issue by ng-life** [jetplugins/yapix#10]
![image](https://user-images.githubusercontent.com/2994263/144467364-9b5d00d1-3924-4d5b-9364-5ed1259592ce.png)

**Comment by lkqm** [comment]
目前更新接口不会进行差异比较，如果差异比较可以实现，将会在下一个版本修复这个问题

**Comment by lkqm** [comment]
0.8版本已经支持，待插件商店审核通过后可下载，也可以通过release离线下载安装。
