### ISSUE TITLE
feat: 代码提交自动触发上传接口文档

### ISSUE THREAD

**Issue by lkqm** [jetplugins/yapix#11]
思路：
1. 扩展代码提交
2. 根据变更解析出关联接口
3. 解析上传

**Comment by lkqm** [comment]
不是 之前想的是代码提交时候解析出变更内容 然后提交后触发api文档上传，但是sdk没有查阅到可以解析出变更代码的得方式

**Comment by BOFA1ex** [comment]
jetbrains的文档不是特别友好.. 你的需求需要借鉴类似Local History(LVCS) 作Diff检查.
另一种思路需要配置相关git和branch信息, 调相关openapi去拿到Diff信息再做解析.

但是我觉得这种方案超出该插件的功能范畴了, 去集成git功能的话. 如果有其他的代码仓库就需要再支持就显得臃肿了.
不如把插件功能开放出去让这些代码仓库流水线接入.
