### ISSUE TITLE
为什么使用rap2上传，进度条一闪而过，在rap2平台上也没看到接口，这块要怎么配置呀？

### ISSUE THREAD

**Issue by 158793034** [jetplugins/yapix#14]

**Comment by lkqm** [comment]
按照以下步骤先确认下：
1. 右下角是否有报错提示
2. 多尝试几个接口（0.8以前有个bug不会解析@XxxMapping 不带参数时）
3. 升级到0.8版本

如果还有问题，可以提供相关的接口代码，插件版本号

**Comment by 158793034** [comment]
可以了，如果我要传到指定的模板上，要如何进行配置呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mario ***@***.***&gt;; 
发送时间: 2021年12月13日(星期一) 晚上6:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jetplugins/yapix] 为什么使用rap2上传，进度条一闪而过，在rap2平台上也没看到接口，这块要怎么配置呀？ (Issue #14)





 
按照以下步骤先确认下：
  
右下角是否有报错提示
 
***@***.*** 不带参数时）
 
升级到0.8版本
  
如果还有问题，可以提供相关的接口代码，插件版本号
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lkqm** [comment]
你应该时说的分类，两种方法设置分类：1.类上使用文档@menu标记, 2.类上文档注释第一行

**Comment by 158793034** [comment]
好的，现在可以上传了，多谢。会持续关注你这个项目
