### ISSUE TITLE
fix: 接口常量字段未被过滤

### ISSUE THREAD

**Issue by BOFA1ex** [jetplugins/yapix#19]
```java
public static boolean isNeedField(PsiField field) {
    PsiModifierList modifierList = field.getModifierList();
    if (modifierList == null || !modifierList.hasExplicitModifier(PsiModifier.STATIC)) {
        return true;
    }
    return false;
}
public interface TestInterface{
    Map<String,Integer> FIELD_MAPPINGS = Map.of("1",2,"3",4);
}
```

![image](https://user-images.githubusercontent.com/30573693/146320748-da83c896-76a7-4084-8728-c15520a0c52c.png)

**Comment by BOFA1ex** [comment]
```java
public static boolean isNeedField(PsiField field) {
    return !field.hasModifier(JvmModifier.STATIC);
}
```

**Comment by lkqm** [comment]
设计如此，响应参数不应该过滤掉final字段，请求参数不考虑，正常情况请求参数不会存在final字段

**Comment by BOFA1ex** [comment]
我想表达的是
接口里定义类变量隐式声明为`modifier static final`
`PsiField#getModifierList#hasExplicitModifier(PsiModifier.STATIC)` 该API行为仅判定字段是否显式声明为`static`.
建议判断逻辑改为 `field.hasModifier(JvmModifier.STATIC)` 可以解决隐式声明的问题.
