### ISSUE TITLE
fix: controller 接口解析异常

### ISSUE THREAD

**Issue by gclm** [jetplugins/yapix#20]
## 效果：
- swagger 解析效果如下：
![image](https://user-images.githubusercontent.com/27618687/146344008-6b2657c5-0588-490a-91dc-9e49911cd159.png)
- yapix 解析效果如下：
![image](https://user-images.githubusercontent.com/27618687/146344148-dbac51dc-22ce-4624-88a8-34a4009d598b.png)

## 原因分析：
> 个人分析的原因如下，仅供参考
- 不支持接口继承解析，目前我们这个项目存在接口继承的操作
![image](https://user-images.githubusercontent.com/27618687/146344702-009b1ac8-ea98-4445-8743-ebceae5dd8fb.png)

## 代码参考
- 目前测试发现这个插件（RedsoftYapiUpload）支持，但是他支持的平台没有 yapix多，所以希望yapix可以支持这个操作

**Comment by lkqm** [comment]
继承问题已经修复，近期会发个版
