### ISSUE TITLE
feat: 新增接口推送策略

### ISSUE THREAD

**Issue by gclm** [jetplugins/yapix#21]
## 问题描述：
目前同一个controller推送两次，就创建了两次不会去重，希望可以新增接口推送策略，支持覆盖更新等操作

**Comment by lkqm** [comment]
正常情况同一个controller是不会推送两次的，需要你具体描述下问题

**Comment by gclm** [comment]
如果controller 发生新增api接口、修改接口描述信息等情况，肯定需要同步controller

**Comment by lkqm** [comment]
有这样功能的，是会推送，老接口查找策略：

**Comment by gclm** [comment]
好的，那我在研究一下，目前我测试发现确实存储重复推送的情况

**Comment by lkqm** [comment]
该问题已经复现，0.9.2版本已修复
