### ISSUE TITLE
feat: 支持更多检验注解

### ISSUE THREAD

**Issue by lkqm** [jetplugins/yapix#25]

**Comment by derotyoung** [comment]
有点意外发现支持javax.validation.constraints.NotNull注解，希望能够支持一下com.fasterxml.jackson.annotation.JsonIgnore等更多注解，同事有个建议，支持的注解能够列举到文档中

**Comment by lkqm** [comment]
哈哈被发现，JsonIgnore这个可以支持，其他还需要什么注解可以说明下

**Comment by derotyoung** [comment]
> 哈哈，没问题。目前也在摸索体验中，这个工具用的最顺手，后续发现了什么问题再来发言

**Comment by MetaYu** [comment]
希望能支持JsonNaming注解呀, 该注解用于转换接口字段序列化命名; 

<img width="653" alt="image" src="https://user-images.githubusercontent.com/45483591/162558432-b5069710-270c-4a97-98f9-dbdbe4bd6b17.png">

**Comment by lkqm** [comment]
> 

好的，最近几天会添加，并发个版

**Comment by lkqm** [comment]
@MetaYu 命名策略，@JsonNaming存在新老api兼容起来比较麻烦，暂时不打算实现
