### ISSUE TITLE
希望支持自定义url前缀

### ISSUE THREAD

**Issue by derotyoung** [jetplugins/yapix#26]
由于是微服务项目，每个微服务在网关都有定义自己的前缀，现在生成的url无法带前缀

**Comment by lkqm** [comment]
能具体说下使用的api管理平台吗？目前yapi平台支持配置单项目的地址前缀的，另外如果是微服务项目，那么在api管理平台是对应多个项目，还是单个项目了？

**Comment by derotyoung** [comment]
> 

使用的yapi，没在文档中看到前缀怎么配置，尝试了下在类上加@prefix和方法上加@path都不行，以为没这个功能，麻烦说明以下如何实现单项目url前缀如何实现。
目前使用上看在每个model下的根目录下都会有.yapix，yapi使用上是可以支持多项目的。

**Comment by lkqm** [comment]
不需要再插件里面配置，yapi平台支持配置路径前缀：点击进入项目 -> 设置 -> 项目设置：接口基本路径

**Comment by derotyoung** [comment]
> 不需要再插件里面配置，yapi平台支持配置路径前缀：点击进入项目 -> 设置 -> 项目设置：接口基本路径

配置后就完全支持多项目了，感谢

**Comment by lkqm** [comment]
好的 不客气
