### ISSUE TITLE
是否有可以Chrome中能正常请求的插件

### ISSUE THREAD

**Issue by xueshuai0922** [jetplugins/yapix#27]
![2ZY3`6U98SHL3AL ~IA)$_P](https://user-images.githubusercontent.com/36756769/159874958-675656f8-2a52-438d-8d93-b5fbb57fad07.png)
现在请求无法返回response

**Comment by lkqm** [comment]
这个项目不是chrome插件项目，是IDEA插件。不过据我使用来看chrome插件YApi-X可以用来解决你这个问题
