### ISSUE TITLE
feat: 希望能支持组合注解的场景

### ISSUE THREAD

**Issue by xyohn** [jetplugins/yapix#29]
作者好
目前业务上，可能会对@Controller(@RestController)在进一步包装
举个例子 定义一个@ValidController的注解 它是 @Valid 和 @Controller 的组合注解 
例如
```java
@Validated
@RestController
public @interface ValidController {

    @AliasFor(annotation = Controller.class) String value() default "";
}
```
这时候 对于加上了这个注解的Controller类 yapix会认为他不是合法的controller 因此不进行接口的上传
想问一下可否加入对这种场景的支持呢
谢谢

**Comment by lkqm** [comment]
这个倒好实现，只是感觉这样自己组合一个注解必要性不大

**Comment by xyohn** [comment]
> 这个倒好实现，只是感觉这样自己组合一个注解必要性不大

标志性的注解在做组合感觉还是挺常用的 😂
就像 @ResponseBody和@Controller做组合得到@RestController 一样 目前我们开发上会把一些基本每个类都会标识的注解做一些组合 一是简化开发 二也减少遗漏😂

**Comment by lkqm** [comment]
好的，最近会支持这个功能

**Comment by xyohn** [comment]
好的 感谢
