### ISSUE TITLE
提交到YApi上的接口状态以及请求的时间参数格式

### ISSUE THREAD

**Issue by LY5216** [jetplugins/yapix#33]
1.通过插件提交到YApi上面的接口状态全部都是未完成，希望有对应的注解或者提交后都是已完成状态

2.通过插件提交到YApi上面的接口的请求参数无论是LocalDate、LocalDateTime、Date 在备注栏都是 yyyy-MM-dd HH:mm:ss 希望LocalDate和LocalDateTime 有区分(如以下两张图片)

![image](https://user-images.githubusercontent.com/49475455/172336019-eaf5bc62-67a7-4aaf-8f63-678560180e45.png)

![image](https://user-images.githubusercontent.com/49475455/172335883-ba348491-9aa3-4507-87e2-6a0707d75a9b.png)

**Comment by lkqm** [comment]
版本0.9.5已支持配置时间类型，待插件商店审核通过后可下载更新（预计1天左右）

**Comment by LY5216** [comment]
首先谢谢大大的回复

其次是关于第一个问题的解释

关于我们后端开发目前接触到的有两种方式

第一种：先定义好接口名称接口参数，前端通过mock方式调用接口处理页面并渲染，后端并行填充接口内部逻辑，逻辑填充完成后，自测通过后再去修改YApi上面接口完成状态，前端再次进行接口复调用。
第二种：后端直接写接口逻辑写好后通过postman等系列方式接口测试工具测试完成后，手动或者插件导入方式将Api接口填充到YApi管理工具上面。


------------------------------------------------------------------
发件人：Mario Luo ***@***.***>
发送时间：2022年6月7日(星期二) 23:32
收件人：jetplugins/yapix ***@***.***>
抄　送：LY5216 ***@***.***>; Author ***@***.***>
主　题：Re: [jetplugins/yapix] 提交到YApi上的接口状态以及请求的时间参数格式 (Issue #33)

1.关于YApi接口状态问题，最主要考虑的是这个功能是否有用，楼主可以说下你的工作流，看是否有必要添加这个功能
 2.关于LocalDate, Time打算新增一个配置全局的格式
