### ISSUE TITLE
推送 RAP2 报错

### ISSUE THREAD

**Issue by jianlong1994** [jetplugins/yapix#37]
IDEA版本：2022.2

推送到RAP2报错
Config file error: Failed making field 'java.util.regex.Pattern#pattern' accessible; either change its visibility or write a custom TypeAdapter for its declaring type

**Comment by lkqm** [comment]
应该是配置文件有问题，请提供下配置文件

**Comment by jiouloucse** [comment]
com.google.gson.JsonIOException: Failed making field 'java.util.regex.Pattern#pattern' accessible; either change its visibility or write a custom TypeAdapter for its declaring type
![image](https://user-images.githubusercontent.com/39786523/181432431-8bbd0b1d-76ea-49f1-bb24-563e7a44987a.png)

**Comment by jiouloucse** [comment]
> 应该是配置文件有问题，请提供下配置文件

com.google.gson.JsonIOException: Failed making field 'java.util.regex.Pattern#pattern' accessible; either change its visibility or write a custom TypeAdapter for its declaring type
![](https://user-images.githubusercontent.com/39786523/181432431-8bbd0b1d-76ea-49f1-bb24-563e7a44987a.png)

**Comment by lkqm** [comment]
gson兼容性问题，新版使用的jdk17下存在这个问题，我看下怎么修复下

**Comment by jiouloucse** [comment]
> gson兼容性问题，新版使用的jdk17下存在这个问题，我看下怎么修复下

感谢！

**Comment by lkqm** [comment]
0.9.5版本已修复，请待插件审核通过后升级插件版本（预计1天左右）
