### ISSUE TITLE
同一个接口多版本并行修改的情况

### ISSUE THREAD

**Issue by lifesign** [jetplugins/yapix#4]
请问下作者有否考虑该情况如何处理

**Comment by lkqm** [comment]
对于同一个接口不同版本，最终上传到接口管理平台只对应一份，似乎没有办法解决这个问题，欢迎提供思路。

另外目前开发中还未遇到过这种情况。

**Comment by lifesign** [comment]
之前本来想通过 tag 来区分，但是貌似同一个路径 yapi 只认一份，就比较蛋疼了
个人开发一般不会遇到，同一个工程不同版本并行，又针对同一个接口有变更，这种情况就会遇到
