### ISSUE TITLE
optimize: 使用开放接口上传到Eolink平台

### ISSUE THREAD

**Issue by lkqm** [jetplugins/yapix#42]
目前使用网页抓包的接口，如果下次还存在接口变动，那么尝试用官方的openapi来实现上传

**Comment by ttxs0109** [comment]
> 目前使用网页抓包的接口，如果下次还存在接口变动，那么尝试用官方的openapi来实现上传

现在登录报需要输入验证码

**Comment by lkqm** [comment]
登录需要验证码已修复 0.9.7版本，插件在审核中，可以在release离线下载
