### ISSUE TITLE
没有创建.yapix文件

### ISSUE THREAD

**Issue by kecikeci** [jetplugins/yapix#44]
![image](https://user-images.githubusercontent.com/32811349/187187265-5f475324-1541-42a7-9a4f-dd3dde0f4efe.png)

点击后没创建yapix文件

![image](https://user-images.githubusercontent.com/32811349/187187369-18a3dafb-e28b-4f3f-a94c-3fb0a062f085.png)

**Comment by kecikeci** [comment]
![image](https://user-images.githubusercontent.com/32811349/187187622-3b5ddb92-7210-4093-b2fc-ce0e24335de7.png)

**Comment by kecikeci** [comment]
> 从文件系统中能否看到，或者刷新项目树试试

![image](https://user-images.githubusercontent.com/32811349/187326867-1f6b886a-19ce-4e19-abd9-d29956678226.png)

没有的

重启idea重试也不行，不知道什么原因

**Comment by lkqm** [comment]
好的，我调试调试，你先手动创建

**Comment by lkqm** [comment]
无法复现，暂时不处理
