### ISSUE TITLE
类上@RequestMapping注解没有method时会报错

### ISSUE THREAD

**Issue by NotEdibleSalt** [jetplugins/yapix#45]
![image](https://user-images.githubusercontent.com/52400896/194683343-a0705843-1a17-490e-90b3-28249eb501de.png)

类上@RequestMapping注解没有method的值，在调用HttpMethod的of方法时会抛出空指针。需要在.map(HttpMethod::of)前面过滤空字符串

**Comment by lkqm** [comment]
实际会遇到吗？我这边测试了不会报错

**Comment by NotEdibleSalt** [comment]
会遇到，但不是所有接口都会出现。

**Comment by NotEdibleSalt** [comment]
> 实际会遇到吗？我这边测试了不会报错

会遇到，但不是所有接口都会出现。

**Comment by NotEdibleSalt** [comment]
> 行 后续会修复这个问题

好的好的
