### ISSUE TITLE
对于同一个对象，使用分组校验，如何区分是否必填？

### ISSUE THREAD

**Issue by whiteS18** [jetplugins/yapix#47]
我在对象中定义了一个id字段，在新增时非必填，在修改时必填，使用了分组校验，但是上传到文档后，在新增的接口还是显示必填
![图片](https://user-images.githubusercontent.com/31566522/194793539-c77e8e24-dfcf-4c8b-b963-079ac4fca1d1.png)
![图片](https://user-images.githubusercontent.com/31566522/194793616-c73efa02-7922-443e-b40b-4861b22db5c2.png)
![图片](https://user-images.githubusercontent.com/31566522/194793660-9d533428-b754-46ac-a225-2af4c7ebd6e9.png)
![图片](https://user-images.githubusercontent.com/31566522/194793729-0358be00-37cf-431f-8b2a-328543d08a75.png)

**Comment by lkqm** [comment]
不支持分组，你可以试试easy-yapi插件

**Comment by lkqm** [comment]
已支持分组，后续会发布一个版本
