### ISSUE TITLE
idea导出接口报too complex

### ISSUE THREAD

**Issue by EdwordJia** [jetplugins/yapix#50]
您好，
idea 版本IntelliJ IDEA 2022.2.3
idea yapi插件 Easy Yapi Tangcent 2.4.7.191.0

错误信息
......is too complex. Blocked by elements reached 1417

**Comment by lkqm** [comment]
是弄错了吗，这个是Yapi X插件地址

**Comment by EdwordJia** [comment]
抱歉，搞错了哈，谢谢
