### ISSUE TITLE
配置了 .yapix 文件，上传 没有任何反应

### ISSUE THREAD

**Issue by jialong5566** [jetplugins/yapix#9]
yapiUrl=http://xxx.com/
yapiProjectId=99
yapiProjectToken=xxxxxx
这还缺什么吗

**Comment by lkqm** [comment]
配置文件是正确的，有两种可能:
1. 请确认光标是否在对应接口方法，或者类上
2. 看右下角是否有错误提示

如果还有使用问题加群沟通，方便些
